---
- name: Copy a netplan config file
  template:
    src: netplancfg.j2
    dest: /etc/netplan/config.yaml
    mode: 0640

- name: Apply netplan config
  shell: netplan apply
  become: true
  async: 30 # Maximum allowed time in Seconds
  poll: 10 # Polling Interval in Seconds
