---
- name: Print architecture
  debug:
    msg: "Architecture: {{ ansible_architecture }}"

- name: Cleanup leftovers from other installs
  apt:
    name:
      - jellyfin
      - jellyfin-ffmpeg
    state: absent
    purge: yes

- name: Add signing key to a specific keyring file
  apt_key:
    url: https://repo.jellyfin.org/jellyfin_team.gpg.key
    keyring: /etc/apt/keyrings/jellyfin.gpg

- name: Add repository into sources list
  apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/jellyfin.gpg] https://repo.jellyfin.org/ubuntu jammy main
    state: present
    filename: jellyfin
  tags:
    - apt

- name: Install apt dependencies
  apt:
    name:
      - jellyfin
    state: present
    update_cache: yes

# - name: Add user "jellyfin"
#   user:
#     name: jellyfin
#     shell: /sbin/nologin
#     create_home: no
#     comment: "Jellyfin Media Server nologin User"
#     state: present
#   become: true

# - name: Creates install dir
#   file:
#     path: /opt/jellyfin
#     owner: jellyfin
#     group: jellyfin
#     state: directory
#     mode: 0744
#   tags:
#     - create-dir

# - name: Download jellyfin package
#   get_url:
#     url: https://repo.jellyfin.org/releases/server/linux/stable/combined/jellyfin_10.8.10_{{ deb_architecture }}.tar.gz
#     dest: /tmp/jellyfin_10.8.10.tar.gz

# - name: Extract jellyfin tarball into /opt
#   ansible.builtin.unarchive:
#     src: /tmp/jellyfin_10.8.10.tar.gz
#     dest: /opt/jellyfin
#     owner: jellyfin
#     group: jellyfin
#     remote_src: true

# - name: Creates install folder symlink
#   file:
#     state: link
#     src: /opt/jellyfin/jellyfin_10.8.10
#     owner: jellyfin
#     group: jellyfin
#     follow: false
#     dest: /opt/jellyfin/jellyfin
#   tags:
#     - create-dir

# - name: Create subdirs for jellyfin data
#   file:
#     state: directory
#     path: "/opt/jellyfin/{{ item }}"
#     owner: jellyfin
#     group: jellyfin
#   with_items:
#     - data
#     - cache
#     - config
#     - log
#   tags:
#     - create-dir

# - name: Download jellyfin-ffmpeg package
#   get_url:
#     url: https://repo.jellyfin.org/releases/server/debian/versions/jellyfin-ffmpeg/5.1.2-5/jellyfin-ffmpeg5_5.1.2-5-buster_{{ deb_architecture }}.deb
#     dest: /tmp/jellyfin-ffmpeg5_5.1.2-5-buster.deb

# - name: Install a .deb package
#   ansible.builtin.apt:
#     deb: /tmp/jellyfin-ffmpeg5_5.1.2-5-buster.deb

# - name: Copy jellyfin start script
#   copy:
#     src: jellyfin.sh
#     dest: /opt/jellyfin/jellyfin.sh
#     owner: jellyfin
#     group: jellyfin
#     mode: 0544

# - name: Copy jellyfin service description
#   copy:
#     src: jellyfin.service
#     dest: /etc/systemd/system/jellyfin.service
#     mode: 0644
#   tags:
#     - systemd

# - name: Reload service jellyfin, in all cases
#   ansible.builtin.systemd:
#     name: jellyfin.service
#     state: reloaded
#   tags:
#     - systemd

# - name: Enable service jellyfin and ensure it is not masked
#   ansible.builtin.systemd:
#     name: jellyfin.service
#     enabled: yes
#     masked: no
#   tags:
#     - systemd

- name: Make sure the service unit is running
  ansible.builtin.systemd:
    state: started
    name: jellyfin.service
  register: jellyfin_output
  tags:
    - systemd

- debug:
    msg: "Jellyfin is {{ jellyfin_output.status.ActiveState | default('') }} since {{ jellyfin_output.status.ActiveEnterTimestamp | default('') }}"
  when: not jellyfin_output.failed
