# SOPS configuration file
# Uses both age and AWS KMS encryption for redundancy
#
# Decryption requires EITHER:
#   - age private key (~/.config/sops/age/keys.txt)
#   - AWS credentials with KMS decrypt permission

creation_rules:
  # Match any .sops.yml file in host_vars or group_vars
  - path_regex: .*(host_vars|group_vars)/.*\.sops\.(yml|yaml)$
    age: age1qr8admz3tpydxtwuefwdggm2vks36e2x5966zj8m84j2elyurdfsdg5jfk
    kms: arn:aws:kms:us-east-1:256935246980:key/e066688f-aa55-470e-9a33-84393e9c4310

  # Match any .sops.yml or .sops.yaml file (fallback)
  - path_regex: .*\.sops\.(yml|yaml)$
    age: age1qr8admz3tpydxtwuefwdggm2vks36e2x5966zj8m84j2elyurdfsdg5jfk
    kms: arn:aws:kms:us-east-1:256935246980:key/e066688f-aa55-470e-9a33-84393e9c4310
