all:
  children:
    aws_vpn_hub:
      hosts:
        vpn-hub:
          # ansible_host defined in host_vars/vpn-hub/secrets.sops.yml

    local:
      hosts:
        localhost:
          ansible_connection: local

    home:
      hosts:
        192.168.15.3:
        192.168.15.6:
        prod-primaria:
        asus-tuf:
        granado-linux-mtz:
        thinkpad-DEV:
        thinkpad-DEV02:
        prod-FTZ:
        prod-SPO:
        approve-prod-sa-east-1:
        kali-mouse:
        mouse:
        omarchy-pc-do-b:
        stremio-rpi:
        raspberry-pi-home:
        raspberry-pi-bravo-vpn:
        oci-vmetrics:
