all:
  children:
    local:
      hosts:
        localhost:
          ansible_connection: local
          ansible_user: paulo
          ansible_python_interpreter: /usr/bin/python3
          ansible_become_pass: !vault |
            $ANSIBLE_VAULT;1.1;AES256
            31653966306237316530393565663630383037383131313033653762346339333034636330616565
            3965666631353762376265393539333634663865336539330a353736393364343163373130633164
            30383730653430633466396133656335313063626364303665373163313734303237336133383135
            6135393566346230350a373361316265623439306233663463383733643535313537346438383063
            6437

    home:
      hosts:
        192.168.15.3:
          ansible_user: paulostation
          desired_ip_address: 192.168.15.3/24
          network_interface_name: enp3s0
        192.168.15.6:
          ansible_user: paulostation

        pc-do-b-vpn:

        sysframe-dev:
          ansible_user: paulao

        approvepay-prod:
          ansible_user: root
          docker_install_compose: true
        # kali-mouse:

        pc-pai:
          ansible_host: 8.13.5.8
          ansible_user: hard
          docker_install_compose: true
          docker_users:
            - hard
        

        ec2-vpn-tunneled:
          docker_install_compose: true
        
        vmetrics-aws:
          ansible_user: ubuntu
          docker_apt_ansible_distribution: ubuntu
          ansible_python_interpreter: /usr/bin/python3
          docker_install_compose: true
          ansible_os_family: Debian
          docker_users:
            - ubuntu
        
        vmetrics-prod:
          ansible_user: ubuntu
          docker_apt_ansible_distribution: ubuntu
          ansible_python_interpreter: /usr/bin/python3
          docker_install_compose: true
          ansible_os_family: Debian
          docker_users:
            - ubuntu
        
        kali-mouse:
          ansible_user: paulo
          docker_install_compose: true
          devices_to_add:
            - device_id: KLXUWIC-5GIZH7B-L4ZE347-V5BBEY5-CNSVPMD-5PIGYP5-6EYWXIR-S7IUIAF
              name: PCdoB
            - device_id: MAQ5YHH-6HEFVUM-25G7JVH-QLGOKIJ-CO2YWW7-2FPS4CQ-HV3OS5F-SEAUVA5
              name: "Asus TUF 15"
            - device_id: VTVVFT7-7Z4OJFD-SF66JLZ-V35OP2K-JLGU2EC-ABN2KFA-WHRO6QK-QXBMKAM
              name: M2007J3SY

        raspberry-pi-home:
          ansible_user: paulostation
          # devices_to_add:
          #   - device_id: KLXUWIC-5GIZH7B-L4ZE347-V5BBEY5-CNSVPMD-5PIGYP5-6EYWXIR-S7IUIAF
          #     name: PCdoB
          #   - device_id: MAQ5YHH-6HEFVUM-25G7JVH-QLGOKIJ-CO2YWW7-2FPS4CQ-HV3OS5F-SEAUVA5
          #     name: "Asus TUF 15"
          #   - device_id: VTVVFT7-7Z4OJFD-SF66JLZ-V35OP2K-JLGU2EC-ABN2KFA-WHRO6QK-QXBMKAM
          #     name: M2007J3SY
          custom_config_dir: /mnt/ext_seagate_hdd/syncthing_configs/config
          custom_data_dir: /mnt/ext_seagate_hdd/syncthing_configs/data
          # syncthing_is_an_upgrade: yes
          docker_install_compose: true
          docker_users:
            - ubuntu

        raspberry-pi-bravo-vpn:
          ansible_user: paulostation
          devices_to_add:
            - device_id: KLXUWIC-5GIZH7B-L4ZE347-V5BBEY5-CNSVPMD-5PIGYP5-6EYWXIR-S7IUIAF
              name: PCdoB
            - device_id: MAQ5YHH-6HEFVUM-25G7JVH-QLGOKIJ-CO2YWW7-2FPS4CQ-HV3OS5F-SEAUVA5
              name: Asus TUF 15
            - device_id: VTVVFT7-7Z4OJFD-SF66JLZ-V35OP2K-JLGU2EC-ABN2KFA-WHRO6QK-QXBMKAM
              name: M2007J3SY

        asus_tuf_a15:
          ansible_host: 10.172.168.7
          ansible_user: paulo
          lokinet_is_an_upgrade: true
          jellyfin_is_an_upgrade: true
