all:
    children:
        oci_homelab:
            hosts:
                136.248.92.196:
                    ansible_user: ubuntu
                    ansible_python_interpreter: /usr/bin/python3
                    # WireGuard peer public keys
                    desktop_wireguard_pubkey: ENC[AES256_GCM,data:aKWeiAkeknkJ2ZwE7RDc6qpcsVG1tBMmhHlu43zgDJk68+CVcDf2sdLWxUU=,iv:UX22NxLIfXhWeCqdx6LKMdCTVo887czSHiOf07XwNYc=,tag:HJ5ktNw+CncnlRva7kOEBw==,type:str]
                    rpi_wireguard_pubkey: ENC[AES256_GCM,data:i4wkQWnnhSQhViNFQetanF7kLO9F+SWf9Zt+eovd7WqXV1GH22oTPF7z050=,iv:T5X4iB5sTygS33HQ1sx6Twz0w8LLHp31sNVac6Mxeho=,tag:GgLz4yZGi+EmPxIpZ82hOQ==,type:str]
                    phone_wireguard_pubkey: ENC[AES256_GCM,data:yQtQH++SowsqB6cmu10inGHBuz3OPwfGDigOoeFQEgufqNQFp1OMGOQEurI=,iv:49uadj2CVJEorL2vDU5sTHnkQjiR8KmNBGYz4+QSki4=,tag:ikyPeVlOk6roEwh7YzuObQ==,type:str]
        local:
            hosts:
                localhost:
                    ansible_connection: local
                    ansible_user: paulo
                    ansible_python_interpreter: /home/paulo/Source_Codes/ansible-playbooks/.venv/bin/python3
                    ansible_become_pass: |
                        $ANSIBLE_VAULT;1.1;AES256
                        31653966306237316530393565663630383037383131313033653762346339333034636330616565
                        3965666631353762376265393539333634663865336539330a353736393364343163373130633164
                        30383730653430633466396133656335313063626364303665373163313734303237336133383135
                        6135393566346230350a373361316265623439306233663463383733643535313537346438383063
                        6437
        home:
            vars:
                ansible_ssh_common_args: -o ForwardAgent=yes
            hosts:
                192.168.15.3:
                    ansible_user: paulostation
                    desired_ip_address: 192.168.15.3/24
                    network_interface_name: enp3s0
                192.168.15.6:
                    ansible_user: paulostation
                prod-primaria:
                    ansible_user: paulao
                asus-tuf:
                    asdf_user: paulao
                    asdf_shell: zsh
                    asdf_plugins:
                        - name: jq
                          version: 1.7.1
                        - name: yq
                          version: 4.44.1
                        - name: k9s
                          version: 0.50.9
                        - name: kubectl
                          version: 1.34.1
                        - name: helm
                          version: 4.0.0
                          repo_url: https://github.com/Antiarchitect/asdf-helm.git
                        - name: github-cli
                          version: 2.83.1
                          repo_url: https://github.com/bartlomiejdanek/asdf-github-cli.git
                granado-linux-mtz:
                    asdf_user: paulao
                    asdf_shell: zsh
                    asdf_plugins:
                        - name: jq
                          version: 1.7.1
                        - name: yq
                          version: 4.44.1
                        - name: k9s
                          version: 0.50.9
                        - name: kubectl
                          version: 1.34.1
                thinkpad-DEV:
                    asdf_user: paulao
                    asdf_shell: zsh
                    asdf_plugins:
                        - name: jq
                          version: 1.7.1
                        - name: yq
                          version: 4.44.1
                        - name: k9s
                          version: 0.50.9
                        - name: kubectl
                          version: 1.34.1
                thinkpad-DEV02:
                    asdf_user: paulao
                    asdf_shell: zsh
                    asdf_plugins:
                        - name: jq
                          version: 1.7.1
                        - name: yq
                          version: 4.44.1
                        - name: k9s
                          version: 0.50.9
                        - name: kubectl
                          version: 1.34.1
                prod-FTZ:
                    asdf_user: paulao
                    asdf_shell: zsh
                    asdf_plugins:
                        - name: jq
                          version: 1.7.1
                        - name: yq
                          version: 4.44.1
                        - name: k9s
                          version: 0.50.9
                        - name: kubectl
                          version: 1.34.1
                        - name: null
                    ansible_ssh_common_args: -o ForwardAgent=yes
                prod-SPO:
                    asdf_user: paulao
                    asdf_shell: zsh
                    asdf_plugins:
                        - name: jq
                          version: 1.7.1
                        - name: yq
                          version: 4.44.1
                        - name: k9s
                          version: 0.50.9
                        - name: kubectl
                          version: 1.34.1
                    ansible_ssh_common_args: -o ForwardAgent=yes
                approve-prod-sa-east-1:
                    customer: approvepayment
                    ansible_host: 54.232.134.166
                    ansible_user: paulao
                    asdf_user: paulao
                    asdf_shell: zsh
                    asdf_plugins:
                        - name: jq
                          version: 1.7.1
                        - name: yq
                          version: 4.44.1
                        - name: k9s
                          version: 0.50.9
                        - name: kubectl
                          version: 1.34.1
                        - name: neovim
                          version: 0.11.4
                    ansible_ssh_common_args: -o ForwardAgent=yes
                kali-mouse:
                    ansible_user: paulo
                    docker_install_compose: true
                    devices_to_add:
                        - device_id: KLXUWIC-5GIZH7B-L4ZE347-V5BBEY5-CNSVPMD-5PIGYP5-6EYWXIR-S7IUIAF
                          name: PCdoB
                        - device_id: MAQ5YHH-6HEFVUM-25G7JVH-QLGOKIJ-CO2YWW7-2FPS4CQ-HV3OS5F-SEAUVA5
                          name: Asus TUF 15
                        - device_id: VTVVFT7-7Z4OJFD-SF66JLZ-V35OP2K-JLGU2EC-ABN2KFA-WHRO6QK-QXBMKAM
                          name: M2007J3SY
                stremio-rpi:
                    ansible_user: paulao
                    ansible_host: 192.168.15.3
                    # Network configuration
                    wired_static_ip: 192.168.15.2/24
                    wifi_ssid: Masamune
                    wifi_password: ENC[AES256_GCM,data:X+wZ8xRxyiX99Vr7IpcBUA==,iv:y0qiOH794YFLFIPzZcEyQo183rSK0svfFtica7HAnTw=,tag:gxdO1xarR3Wg54epw1X7jQ==,type:str]
                    wifi_static_ip: 192.168.15.3/24
                    wifi_country: BR
                    # WireGuard client configuration
                    oci_public_ip: 136.248.92.196
                    oci_wireguard_pubkey: ENC[AES256_GCM,data:hUeqiaT00SSksd+hfVA49dWOpDOt20GIB91n5j6cwew75TYSceXils26/LY=,iv:A8XJOfqBytVdH0nHJBmJK8S1zTXupuQaGjM0treaYDE=,tag:MxmcwkDf+y1p3WBsTswkmA==,type:str]
                raspberry-pi-home:
                    ansible_user: paulostation
                    # devices_to_add:
                    #   - device_id: KLXUWIC-5GIZH7B-L4ZE347-V5BBEY5-CNSVPMD-5PIGYP5-6EYWXIR-S7IUIAF
                    #     name: PCdoB
                    #   - device_id: MAQ5YHH-6HEFVUM-25G7JVH-QLGOKIJ-CO2YWW7-2FPS4CQ-HV3OS5F-SEAUVA5
                    #     name: "Asus TUF 15"
                    #   - device_id: VTVVFT7-7Z4OJFD-SF66JLZ-V35OP2K-JLGU2EC-ABN2KFA-WHRO6QK-QXBMKAM
                    #     name: M2007J3SY
                    custom_config_dir: /mnt/ext_seagate_hdd/syncthing_configs/config
                    custom_data_dir: /mnt/ext_seagate_hdd/syncthing_configs/data
                    # syncthing_is_an_upgrade: yes
                    docker_install_compose: true
                    docker_users:
                        - ubuntu
                raspberry-pi-bravo-vpn:
                    ansible_user: paulostation
                    devices_to_add:
                        - device_id: KLXUWIC-5GIZH7B-L4ZE347-V5BBEY5-CNSVPMD-5PIGYP5-6EYWXIR-S7IUIAF
                          name: PCdoB
                        - device_id: MAQ5YHH-6HEFVUM-25G7JVH-QLGOKIJ-CO2YWW7-2FPS4CQ-HV3OS5F-SEAUVA5
                          name: Asus TUF 15
                        - device_id: VTVVFT7-7Z4OJFD-SF66JLZ-V35OP2K-JLGU2EC-ABN2KFA-WHRO6QK-QXBMKAM
                          name: M2007J3SY
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hz38nr8hn2qtasd5kd0e5r3fxuxv098mx4y9c58789kzaxsr0gnsmxsg9r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEekl2eWdvMExDdnh6a3pZ
            T2U1MUJzZGtaUnNKTDJJYnBxSXJsQXEyVVc0CnkwWUw2NGVrdEFhYlZONVFGTkNP
            TjhSTXcwelNRNUNkSGZBdTRzNnlVa3cKLS0tIGMzMC9Wd0ZVMU1SR1BBdTc0TW1X
            NkZnS1pSUHNudm5GRnFCRVIybUJ2WjgKAatsopA0Rf51k53YGovQ95i0tI2SQ9aE
            DIPKCdKuNtGOj0MfTEapMs1wxrv9Gcsdlx4VKC4z5PyAsNE6schXmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T16:25:33Z"
    mac: ENC[AES256_GCM,data:R242cu41UTcEOhhGnzvhhDzYnOfQeXXpilsve8XhmIIjzvZ6kY/SRlljHFnRD73DXf3qY498niMj9XE3rpQrEBTReKWSwJT0p7OQk8zglWODbhft9180A6SDgH8IVRvrMV93xH7BrZ6ts4AbGKuHkNIRR2eMKOQ57ocgZMFkXA4=,iv:6jYMMwrfkS8LxPxuOIGjsAFTB0ncYL1O7slyWTS3jes=,tag:ys1sQAZ+He82fA12FhCxzQ==,type:str]
    pgp: []
    encrypted_regex: ^(.*password.*|.*secret.*|.*token.*|.*key.*)$
    version: 3.9.1
