all:
  children:
    local:
      hosts:
        localhost:
          ansible_connection: local
    home:
      hosts:
        192.168.15.3:
          ansible_user: paulostation
          desired_ip_address: 192.168.15.3/24
          network_interface_name: enp3s0
        192.168.15.6:
          ansible_user: paulostation

        asus_tuf_a15:
          ansible_host: 10.172.168.7
          ansible_user: paulo
          lokinet_is_an_upgrade: true
          jellyfin_is_an_upgrade: true
