all:
    children:
        aws_vpn_hub:
            hosts:
                98.88.176.1:
                    ansible_user: ubuntu
                    ansible_python_interpreter: /usr/bin/python3
                    # WireGuard peer public keys
                    desktop_wireguard_pubkey: ENC[AES256_GCM,data:GxzxgrZa2Np0GjT/2e+Oowi4JRFqMAL04RveJzq+fqENurSy00JrkRytQ04=,iv:PqWZhsQlt3lOIPdgbMyshK9V/crSAk4uuLZv9V2t/1E=,tag:lsUgwIwiQQZAMb9jyK4dsQ==,type:str]
                    rpi_wireguard_pubkey: ENC[AES256_GCM,data:dx6ixZ/AdkhfTzrj6EWF9cd/9aFozDMasITXlR4fGSAmXpR7Pary2okdikU=,iv:/nBJ045B6HC1hefG66JyuLP2pONucBoxu3v5LGun8cQ=,tag:y8qGwqqvJPOjoqBbPihn4Q==,type:str]
                    phone_wireguard_pubkey: ENC[AES256_GCM,data:SxZcs9F0ymNrIbfxpiyfUHCYnMR9h5c/unaACnyDlKJPiEmpuHrQ16cb5mc=,iv:RPFnlz/lfSS+rnj1isr7ydNVMX3vRhFu2BirpaJZ2cA=,tag:OE/BoHgx3nSy7K3/IXG+yA==,type:str]
        local:
            hosts:
                localhost:
                    ansible_connection: local
                    ansible_user: paulo
                    ansible_python_interpreter: /home/paulo/Source_Codes/ansible-playbooks/.venv/bin/python3
                    ansible_become_pass: ENC[AES256_GCM,data:jdVPNV8+68g9A4YXpzF36WjRse3wW1NuSn0DnCntO2xA2QSKQIRZ4Uis2cPeB4I/t4nOtp5f9wsL9NqaLaR+KSxw/O4DwzS3kiVT8fcMAlp4sXYNiPpeWsRwamREOcaclpJqIYH6Sw91Wro1nBqhQ/jWTJ8AIIECtiXbaKS+2aL+BABxw4cCqAMmAmhrkXE6zsqx4MVLKA6/kcDLQ6/t69HoZKhSeI2464zuoI9icj5js2hpQYXR+huWiH1dyaBulL+YWMqz8DOBGE/pmSxhBoJBRbx/iNc+3tEa34ooQxS++rYTcqleJBwIUEndwZkfjJ226+kh4zZfCEq8k7UGFdvY/hSJccTIbzQ4+CzhyRS3vP2Cb7FiMhTKD409BJw7qukpzIBmsz/RXX2cXCpYT9gZE0ZQarEI/nrER1SViu5JYAFDSinj4wA3r7CfWnXERKWFVvuL2dalSDzt4nWV9QoOCw==,iv:rQ7t9G2VstkZRjHy/15rgDYT4Aj8T4ZblCmNdXIXggo=,tag:7Sbx6Egvw81xx9CNOSJ21g==,type:str]
        home:
            vars:
                ansible_ssh_common_args: -o ForwardAgent=yes
                chezmoi_github_username: paulostation
                atuin_username: paulostation
                atuin_password: ENC[AES256_GCM,data:RAOugVmYG3FIg/0oMKLDh+sjSps=,iv:2GVl+qa5kiSyb7H7cLj8zRLEW+VTDh4rwRtJTPav5io=,tag:vavVYCYVbFIr6CgoTzi2nw==,type:str]
                atuin_email: dns.breezy309@simplelogin.com
                atuin_key: ENC[AES256_GCM,data:QMWH79mmAP7TMPtK/Xi498klkoxbtoJXtg+bhXEzG0PYw1HSCZNeZPYX5llJypeIlEaQuYf6/kA89T48aLTjFGQSjBNxSo8Myxx2eyWs4XML/JF4f+MBFm153S2ghujRsIXO5WIq+DRy/PvB5x+rNasi0elA44Et1GJ+r1h5AH4S6362lgQjhV5pgXN2ILU46D7ovmY=,iv:mejkJ2dfmTaZSxHq+kk74L428YNtdZasXdRRBwylHms=,tag:CcankDdS7O2fHpvKo5AsaQ==,type:str]
            hosts:
                192.168.15.3:
                    ansible_user: paulostation
                    desired_ip_address: 192.168.15.3/24
                    network_interface_name: enp3s0
                192.168.15.6:
                    ansible_user: paulostation
                prod-primaria:
                    ansible_user: paulao
                asus-tuf:
                    asdf_user: paulao
                    asdf_shell: zsh
                    asdf_plugins:
                        - name: jq
                          version: 1.7.1
                        - name: yq
                          version: 4.44.1
                        - name: k9s
                          version: 0.50.9
                        - name: kubectl
                          version: 1.34.1
                        - name: helm
                          version: 4.0.0
                          repo_url: https://github.com/Antiarchitect/asdf-helm.git
                        - name: github-cli
                          version: 2.83.1
                          repo_url: https://github.com/bartlomiejdanek/asdf-github-cli.git
                granado-linux-mtz:
                    asdf_user: paulao
                    asdf_shell: zsh
                    asdf_plugins:
                        - name: jq
                          version: 1.7.1
                        - name: yq
                          version: 4.44.1
                        - name: k9s
                          version: 0.50.9
                        - name: kubectl
                          version: 1.34.1
                thinkpad-DEV:
                    asdf_user: paulao
                    asdf_shell: zsh
                    asdf_plugins:
                        - name: jq
                          version: 1.7.1
                        - name: yq
                          version: 4.44.1
                        - name: k9s
                          version: 0.50.9
                        - name: kubectl
                          version: 1.34.1
                thinkpad-DEV02:
                    asdf_user: paulao
                    asdf_shell: zsh
                    asdf_plugins:
                        - name: jq
                          version: 1.7.1
                        - name: yq
                          version: 4.44.1
                        - name: k9s
                          version: 0.50.9
                        - name: kubectl
                          version: 1.34.1
                prod-FTZ:
                    asdf_user: paulao
                    asdf_shell: zsh
                    asdf_plugins:
                        - name: jq
                          version: 1.7.1
                        - name: yq
                          version: 4.44.1
                        - name: k9s
                          version: 0.50.9
                        - name: kubectl
                          version: 1.34.1
                    ansible_ssh_common_args: -o ForwardAgent=yes
                prod-SPO:
                    asdf_user: paulao
                    asdf_shell: zsh
                    asdf_plugins:
                        - name: jq
                          version: 1.7.1
                        - name: yq
                          version: 4.44.1
                        - name: k9s
                          version: 0.50.9
                        - name: kubectl
                          version: 1.34.1
                    ansible_ssh_common_args: -o ForwardAgent=yes
                approve-prod-sa-east-1:
                    customer: approvepayment
                    ansible_host: 54.232.134.166
                    ansible_user: paulao
                    asdf_user: paulao
                    asdf_shell: zsh
                    asdf_plugins:
                        - name: jq
                          version: 1.7.1
                        - name: yq
                          version: 4.44.1
                        - name: k9s
                          version: 0.50.9
                        - name: kubectl
                          version: 1.34.1
                        - name: neovim
                          version: 0.11.4
                    ansible_ssh_common_args: -o ForwardAgent=yes
                kali-mouse:
                    ansible_user: paulo
                    docker_install_compose: true
                    devices_to_add:
                        - device_id: KLXUWIC-5GIZH7B-L4ZE347-V5BBEY5-CNSVPMD-5PIGYP5-6EYWXIR-S7IUIAF
                          name: PCdoB
                        - device_id: MAQ5YHH-6HEFVUM-25G7JVH-QLGOKIJ-CO2YWW7-2FPS4CQ-HV3OS5F-SEAUVA5
                          name: Asus TUF 15
                        - device_id: VTVVFT7-7Z4OJFD-SF66JLZ-V35OP2K-JLGU2EC-ABN2KFA-WHRO6QK-QXBMKAM
                          name: M2007J3SY
                mouse:
                    ansible_host: 192.168.15.115
                    ansible_user: paulao
                omarchy-pc-do-b:
                    ansible_connection: local
                    ansible_become_pass: ENC[AES256_GCM,data:8mMllUbh9j7bJupDHTM/Yw==,iv:HLX6wStukdCAUU5bFtmkbAeslObv4JDY3KHhaxQ89G0=,tag:uCGt1oMvCqwWuOJ7b3N12g==,type:str]
                    ansible_user: paulao
                    asdf_user: paulao
                    asdf_shell: zsh
                    yazi_user: paulao
                    yazi_shell: zsh
                    asdf_plugins:
                        - name: jq
                          version: 1.7.1
                        - name: yq
                          version: 4.44.1
                stremio-rpi:
                    ansible_user: paulao
                    ansible_host: 192.168.15.3
                    # Network configuration
                    wired_static_ip: 192.168.15.2/24
                    wifi_ssid: Masamune
                    wifi_password: ENC[AES256_GCM,data:BJpWnRfZmAgdOJx3IcLm7w==,iv:KjvXBGUiGIokRfbfX/W4dB4A+R4DMO4qm3DUEtyS8KQ=,tag:6xrMEY/Y4Ep8NWp1+9UTtA==,type:str]
                    wifi_static_ip: 192.168.15.3/24
                    wifi_country: BR
                    # WireGuard client configuration (VPN hub: vpn.paulo.software)
                    vpn_server_ip: 98.88.176.1
                    # Will be updated after VPN hub is configured
                    vpn_server_pubkey: ""
                raspberry-pi-home:
                    ansible_user: paulostation
                    # devices_to_add:
                    #   - device_id: KLXUWIC-5GIZH7B-L4ZE347-V5BBEY5-CNSVPMD-5PIGYP5-6EYWXIR-S7IUIAF
                    #     name: PCdoB
                    #   - device_id: MAQ5YHH-6HEFVUM-25G7JVH-QLGOKIJ-CO2YWW7-2FPS4CQ-HV3OS5F-SEAUVA5
                    #     name: "Asus TUF 15"
                    #   - device_id: VTVVFT7-7Z4OJFD-SF66JLZ-V35OP2K-JLGU2EC-ABN2KFA-WHRO6QK-QXBMKAM
                    #     name: M2007J3SY
                    custom_config_dir: /mnt/ext_seagate_hdd/syncthing_configs/config
                    custom_data_dir: /mnt/ext_seagate_hdd/syncthing_configs/data
                    # syncthing_is_an_upgrade: yes
                    docker_install_compose: true
                    docker_users:
                        - ubuntu
                raspberry-pi-bravo-vpn:
                    ansible_user: paulostation
                    devices_to_add:
                        - device_id: KLXUWIC-5GIZH7B-L4ZE347-V5BBEY5-CNSVPMD-5PIGYP5-6EYWXIR-S7IUIAF
                          name: PCdoB
                        - device_id: MAQ5YHH-6HEFVUM-25G7JVH-QLGOKIJ-CO2YWW7-2FPS4CQ-HV3OS5F-SEAUVA5
                          name: Asus TUF 15
                        - device_id: VTVVFT7-7Z4OJFD-SF66JLZ-V35OP2K-JLGU2EC-ABN2KFA-WHRO6QK-QXBMKAM
                          name: M2007J3SY
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:256935246980:key/e066688f-aa55-470e-9a33-84393e9c4310
          created_at: "2026-01-15T01:24:11Z"
          enc: AQICAHgjwqjDnIXgmYlFdWyIYvm4WlOsAtus7cSnwyRjnk1BLwE0Y7OOyVQK+Ofk3xdTcvQLAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMnsBFLNaVVufGpoQmAgEQgDs4Z3BtjK5WlDGo8ZovQ000jUPGxOFsfat17Y++zRN3/FXncXXJHY1Cm4RT737NnYTdxKbK885Ris9LpQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18y8alr4hmg0cupmqwlzjgrmwn495q74275jfk4j4hyvlgv80n3vsc8th8g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUUlTVnBwdTVSQW9KaFBI
            VDlOc3ZKVWNLdzNCbU9rREk4a21VdElUOGxJCmRPWWpTVThYUlQyKzQxNEFTLzhu
            SWtKd3lkL05iZ0dxVlZMT0cxMTFnaGcKLS0tIDlyMmxyNEZWVUl6R0VqY1BZZUxl
            UzE1ZkZoQm9tY1pmS2RaRkViRVJ0ME0KwPh94Z7DKUPxXnCM/AaBqF9bMupViNYv
            Q314iZLIJmSF6fnTlKlx+xJkL5HbRKaqadQRIqrj5fGF/ZETZ7TGkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-15T01:24:12Z"
    mac: ENC[AES256_GCM,data:UCzBSZh1tYihsGD0hEfP0MXqFN+C1rGXAHS6mhBSD6pvrrD6gKywm8PvhUwmFMNl2CpG6xBuZd2daYMw+yJqiNaw57Mpg7CtdaKu00GpBVZ7E2oc9y/RA3DmbgUhK4BDNBOju4t+oz4fJEiY2XgmNNDCzsusL0CVesY+Rdp54u8=,iv:F7RV9z/yasBW+Af/Fn7WKfQQ5D0/lT3PGcYoNAQwfVs=,tag:GwlKOagbkJ+n1hm6YHKNMg==,type:str]
    pgp: []
    encrypted_regex: ^(ansible_become_pass|atuin_password|atuin_key|wifi_password|.*_wireguard_pubkey)$
    version: 3.9.1
