all:
  children:
    local:
      hosts:
        localhost:
          ansible_connection: local
    home:
      hosts:
        192.168.15.3:
          ansible_user: paulostation
        192.168.15.6:
          ansible_user: pi
