ansible_host: ENC[AES256_GCM,data:Lkh9ghdW8/Pv0ojPE5k=,iv:52yN0XW38yFv6Ui/yxA7F/iax4xWwoJ8AuFIQ8XW/cc=,tag:5LVDmdhdHKAJkXNkj4Tbdg==,type:str]
ansible_user: ENC[AES256_GCM,data:KAECBnxD,iv:1UlfUu1cqFlHvQxQU6Ng6E1CokBttKhVH++1XPI8EMw=,tag:A0nDRUlcO6Im2mFOsQRQJw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:I7b89TeSZFyjBk5PpM1tjw==,iv:fgOJ1eBeeNjJs93s7wde2HUL2pgjiLKyDHNYIgbN82s=,tag:gYQr5RJsgdi7u38o5EHXYA==,type:str]
wireguard_client_ip: ENC[AES256_GCM,data:g8/Db555/xHHkQ==,iv:MMcirO3St3fh8W82RjRNv3B8iF9jvjJ7YRrneeS6k8M=,tag:BcheRgg/QsZD/4YJf/eSOA==,type:str]
vpn_server_ip: ENC[AES256_GCM,data:9Nian845smo+xsM=,iv:jREI/0emd2g7G+cnmyf+UNtRN+eLiQrXnB3m+hJoJk8=,tag:L6PCWiCa/BTuzEM9lWr5ug==,type:str]
vpn_server_pubkey: ENC[AES256_GCM,data:fRpej6/xMCxl92nnElma9fEn0vpJ9IXF9JQlcr975XoyRrZqFWhTJQupaIM=,iv:kqOeRk7ZcptXKK07IN8dxEW3qvunEg/s5gpP0oEY7j0=,tag:jum0TtofiVZemIAcV5Avgg==,type:str]
wireguard_dns: ENC[AES256_GCM,data:lXieAYeU+OvFoA==,iv:lj0/e3DKLspkWDLCTtAkpy9VyOscGbtL/hbolaJKEjE=,tag:4XmFJX0t1alzXTw5euOdaw==,type:str]
wireguard_dns_domains:
    - ENC[AES256_GCM,data:eTtP886JN39F+pUmCCR59EFz,iv:m82tPC+1dt7G74bxy8lKwHFXry+E3xGkzLKzrdXfYdM=,tag:jqZDZUMcp29PIFnDeK/3Nw==,type:str]
    - ENC[AES256_GCM,data:hyo/IAZzTY+9JMKwqqSK5Q+6pGAJ,iv:rB9IFyN/Hec3L49uyyuUMt53Kx0z6pLrbEeHTCyynvc=,tag:dk+xcUcXVDvhR02UkRysnA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:256935246980:key/e066688f-aa55-470e-9a33-84393e9c4310
          created_at: "2026-02-07T17:50:25Z"
          enc: AQICAHgjwqjDnIXgmYlFdWyIYvm4WlOsAtus7cSnwyRjnk1BLwErzWT+celmmObObuVjrbYcAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMep+pT3soRafsZjaaAgEQgDtbMiLaZlhXKXMxrCsY7kCLJxPNMMaLb10Ku7VExshE9kkwreXoAjS0DdW2xilwVKB88G2lcEjwcowSkg==
          aws_profile: ""
    age:
        - recipient: age1qr8admz3tpydxtwuefwdggm2vks36e2x5966zj8m84j2elyurdfsdg5jfk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2eENNbE81b0RLUEJxRlJH
            VCtFUldGS2ttdFl3aW81MTZreUd1S0VCTkdRCk80ZnBKZWhpbjluaktla3NNZ0lj
            Z1lFTlF2NFErUFF0YXgrRXBLNldrcUUKLS0tIHhIeERqdVphcDNXSkVkUWV6bzdE
            M05scEhTa093ZUhsOVZhZWZ1SUIyOHMK6/LH50CvAA19+zawnPgMNqKrJg6T2uiY
            nuDxx1IotqlmOFGL6i1v6ZqW6CIdqTrxXDz7CvOy/PKf7AlfT+Hvhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T17:50:26Z"
    mac: ENC[AES256_GCM,data:RIzMSonpGuAM3jrSbML0ZNJ1Alr7yW3upuEaGIe4CBGWlvvANs+tQ9W805SBGOv0qykgGT8QIaNnKIC12CFEnAhZUGIwKwFuHt8/DgGczW4WzF5NOqZR3GRSDbKsyUVtEubY3ClWZNsgW04Lad0OfmvuSbKvR6APg8NryUUOkWA=,iv:o76MHYDERsJBSJLJGSuPS/2uZKdrD5jpQqlkZB6Gc2w=,tag:21fn1DxzQL3mdhOfHNETZg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
