#!/bin/bash
export QEMU_BINARY="/opt/qemu-kvm/qemu-8.1.1/build/qemu-system-x86_64"

# Check if the last argument is a dash and remove it
if [ "$#" -gt 0 ] && [ "${!#}" = "-" ]; then
    set -- "${@:1:($#-1)}"
fi

exec "$QEMU_BINARY" "$@"
